Convert tabs to spaces
Unifying this codebase

diff --git a/scripts/fetch_and_build_deb b/scripts/fetch_and_build_deb
--- a/scripts/fetch_and_build_deb
+++ b/scripts/fetch_and_build_deb
@@ -16,7 +16,7 @@ builddir=$(pwd)
 
 # outputs usage message on specified device before exiting with provided status
 usage() {
-	cat << 'E_O_USAGE' >&"$1"
+    cat << 'E_O_USAGE' >&"$1"
 usage: fetch_and_build_deb project build_type build_directory
 
     project : 'citus', 'enterprise', or 'rebalancer'
@@ -28,7 +28,7 @@ the latest 'master' commit, and any other type is interpreted as a git ref to
 facilitate building one-off packages for customers.
 E_O_USAGE
 
-	exit "${2}";
+    exit "${2}";
 }
 
 # sets the next version variable used during non-release builds
@@ -38,11 +38,11 @@ setnextversion() {
 }
 
 if [ "$#" -eq 1 ] && [ "${1}" = '-h' ]; then
-	usage $stdout $success
+    usage $stdout $success
 fi
 
 if [ "$#" -ne 2 ]; then
-	usage $stderr $badusage
+    usage $stderr $badusage
 fi
 
 case "${1}" in
@@ -59,9 +59,9 @@ case "${1}" in
         packagename='citus-rebalancer'
         ;;
     *)
-		echo "$0: unknown project -- ${1}" >&2
-		usage $stderr $badusage
-		;;
+        echo "$0: unknown project -- ${1}" >&2
+        usage $stderr $badusage
+        ;;
 esac
 
 echo "header=\"Authorization: token ${GITHUB_TOKEN}\"" > ~/.curlrc
@@ -79,7 +79,7 @@ case "${2}" in
         gitsha=$(curl -s "https://api.github.com/repos/${repopath}/git/refs/tags/${releasetag}" | \
                  jq -r '.object.sha')
         if [ "${gitsha}" == 'null' ]; then
-        	echo "$0: could not determine commit for git tag ${releasetag}" >&2
+            echo "$0: could not determine commit for git tag ${releasetag}" >&2
             exit $failure
         fi
 
@@ -87,7 +87,7 @@ case "${2}" in
                    "https://api.github.com/repos/${repopath}/git/tags/${gitsha}" | \
                    jq -r '.verification.verified')
         if [ "${verified}" != 'true' ]; then
-        	echo "$0: could not verify signature for git tag ${releasetag}" >&2
+            echo "$0: could not verify signature for git tag ${releasetag}" >&2
             exit $failure
         fi
         ;;
@@ -110,7 +110,7 @@ case "${2}" in
         gitsha=$(curl -sfH 'Accept:application/vnd.github.v3.sha' \
                  "https://api.github.com/repos/${repopath}/commits/${ref}")
         if [ "${?}" -ne 0 ]; then
-        	echo "$0: could not determine commit for git ref ${ref}" >&2
+            echo "$0: could not determine commit for git ref ${ref}" >&2
             exit $failure
         fi
         set -e
diff --git a/scripts/fetch_build_files b/scripts/fetch_build_files
--- a/scripts/fetch_build_files
+++ b/scripts/fetch_build_files
@@ -17,7 +17,7 @@ download=$(mktemp)
 
 # outputs usage message on specified device before exiting with provided status
 usage() {
-	cat << 'E_O_USAGE' >&"$1"
+    cat << 'E_O_USAGE' >&"$1"
 usage: fetch_build_files project format target_directory
 
     project : 'citus', 'enterprise', or 'rebalancer'
@@ -27,15 +27,15 @@ fetch_build_files fetches files needed to package a specified Citus project for
 a specified software packaging system.
 E_O_USAGE
 
-	exit "${2}";
+    exit "${2}";
 }
 
 if [ "$#" -eq 1 ] && [ "${1}" = '-h' ]; then
-	usage $stdout $success
+    usage $stdout $success
 fi
 
 if [ "$#" -ne 3 ]; then
-	usage $stderr $badusage
+    usage $stderr $badusage
 fi
 
 case "${1}" in
@@ -43,35 +43,35 @@ case "${1}" in
         project=${1}
         ;;
     *)
-		echo "$0: unknown project -- ${1}" >&2
-		usage $stderr $badusage
-		;;
+        echo "$0: unknown project -- ${1}" >&2
+        usage $stderr $badusage
+        ;;
 esac
 
 case "${2}" in
-	deb)
-		format='debian'
-		;;
-	rpm)
-		format='redhat'
-		;;
+    deb)
+        format='debian'
+        ;;
+    rpm)
+        format='redhat'
+        ;;
     *)
-		echo "$0: unknown format -- ${2}" >&2
-		usage $stderr $badusage
-		;;
+        echo "$0: unknown format -- ${2}" >&2
+        usage $stderr $badusage
+        ;;
 esac
 
 targetdir=$3
 # validate inputs
 if ! [ -d "${targetdir}" ]; then
-	echo "$0: ${targetdir}: Is not a directory" >&2
-	exit $noinput
+    echo "$0: ${targetdir}: Is not a directory" >&2
+    exit $noinput
 elif [ ! -e "${targetdir}" ]; then
-	echo "$0: ${targetdir}: No such file" >&2
-	exit $noinput
+    echo "$0: ${targetdir}: No such file" >&2
+    exit $noinput
 elif [ ! -r "${targetdir}" ]; then
-	echo "$0: ${targetdir}: Permission denied" >&2
-	exit $noinput
+    echo "$0: ${targetdir}: Permission denied" >&2
+    exit $noinput
 fi
 
 downloadurl="${packagingurl}/archive/${format}-${project}.tar.gz"
@@ -80,8 +80,8 @@ downloadurl="${packagingurl}/archive/${format}-${project}.tar.gz"
 httpcode=$(curl -sL "${downloadurl}" -w "%{http_code}" -o "${download}")
 
 if [ "${httpcode}" -ne 200 ]; then
-	echo "$0: could not fetch build tarball from ${downloadurl}" >&2
-	echo "$0: HTTP code was: ${httpcode}" >&2
+    echo "$0: could not fetch build tarball from ${downloadurl}" >&2
+    echo "$0: HTTP code was: ${httpcode}" >&2
     exit $failure
 fi
 
diff --git a/scripts/parse_repo_path b/scripts/parse_repo_path
--- a/scripts/parse_repo_path
+++ b/scripts/parse_repo_path
@@ -14,7 +14,7 @@ noinput=66
 
 # outputs usage message on specified device before exiting with provided status
 usage() {
-	cat << 'E_O_USAGE' >&"$1"
+    cat << 'E_O_USAGE' >&"$1"
 usage: parse_repo_path project format build_directory
 
     project : 'citus', 'enterprise', or 'rebalancer'
@@ -24,29 +24,29 @@ parse_repo_path extracts the GitHub repo path (owner/project) for a specified
 project and software packaging system.
 E_O_USAGE
 
-	exit "${2}";
+    exit "${2}";
 }
 
 # validates file containing source
 validatefile() {
     if [ -d "$1" ]; then
-    	echo "$0: $1: Is a directory" >&2
-    	exit $noinput
+        echo "$0: $1: Is a directory" >&2
+        exit $noinput
     elif [ ! -e "$1" ]; then
-    	echo "$0: $1: No such file" >&2
-    	exit $noinput
+        echo "$0: $1: No such file" >&2
+        exit $noinput
     elif [ ! -r "$1" ]; then
-    	echo "$0: $1: Permission denied" >&2
-    	exit $noinput
+        echo "$0: $1: Permission denied" >&2
+        exit $noinput
     fi
 }
 
 if [ "$#" -eq 1 ] && [ "${1}" = '-h' ]; then
-	usage $stdout $success
+    usage $stdout $success
 fi
 
 if [ "$#" -ne 3 ]; then
-	usage $stderr $badusage
+    usage $stderr $badusage
 fi
 
 case "${1}" in
@@ -60,35 +60,35 @@ case "${1}" in
         specfile='citus-rebalancer.spec'
         ;;
     *)
-		echo "$0: unknown project -- ${1}" >&2
-		usage $stderr $badusage
-		;;
+        echo "$0: unknown project -- ${1}" >&2
+        usage $stderr $badusage
+        ;;
 esac
 
 builddir=$3
 case "${2}" in
-	deb)
+    deb)
         copyright="${builddir}/debian/copyright"
         validatefile "${copyright}"
         set +e
         repopath=$(awk '/^Source:/{print $NF}' "${copyright}" | egrep -o '[^/]+/[^/]+$')
         set -e
-		;;
-	rpm)
+        ;;
+    rpm)
         specfile="${builddir}/${specfile}"
         validatefile "${specfile}"
         set +e
         repopath=$(awk '/^Source0:/{print $NF}' "${specfile}" | egrep -o 'citusdata/[^/]+')
         set -e
-		;;
+        ;;
     *)
-		echo "$0: unknown format -- ${2}" >&2
-		usage $stderr $badusage
-		;;
+        echo "$0: unknown format -- ${2}" >&2
+        usage $stderr $badusage
+        ;;
 esac
 
 if [ -z "${repopath}" ]; then
-	echo "$0: could not determine repo path" >&2
+    echo "$0: could not determine repo path" >&2
     exit $failure
 fi
 
