Add code to parse repo path

diff --git a/scripts/parse_repo_path b/scripts/parse_repo_path
--- a/scripts/parse_repo_path
+++ b/scripts/parse_repo_path
@@ -15,19 +15,19 @@ noinput=66
 # outputs usage message on specified device before exiting with provided status
 usage() {
 	cat << 'E_O_USAGE' >&"$1"
-usage: parse_latest_release project format build_directory
+usage: parse_repo_path project format build_directory
 
     project : 'citus', 'enterprise', or 'rebalancer'
     format : 'deb' or 'rpm'
 
-parse_latest_release extracts the latest stable release from the build files
-for a specified project and software packaging system.
+parse_repo_path extracts the GitHub repo path (owner/project) for a specified
+project and software packaging system.
 E_O_USAGE
 
 	exit "${2}";
 }
 
-# validates file containing changelog
+# validates file containing source
 validatefile() {
     if [ -d "$1" ]; then
     	echo "$0: $1: Is a directory" >&2
@@ -68,17 +68,17 @@ esac
 builddir=$3
 case "${2}" in
 	deb)
-        changelog="${builddir}/debian/changelog"
-        validatefile "${changelog}"
+        copyright="${builddir}/debian/copyright"
+        validatefile "${copyright}"
         set +e
-        latest=$(egrep -o '\([^\(\)]+\)' "${changelog}" | tr -d '()' | head -n 1)
+        repopath=$(awk '/^Source:/{print $NF}' "${copyright}" | egrep -o '[^/]+/[^/]+$')
         set -e
 		;;
 	rpm)
-        changelog="${builddir}/${specfile}"
-        validatefile "${changelog}"
+        specfile="${builddir}/${specfile}"
+        validatefile "${specfile}"
         set +e
-        latest=$(awk '/^%changelog/{m=1;next}m' "${changelog}" | awk '/^*/{print $NF}' | head -n 1)
+        repopath=$(awk '/^Source0:/{print $NF}' "${specfile}" | egrep -o 'citusdata/[^/]+')
         set -e
 		;;
     *)
@@ -87,9 +87,9 @@ case "${2}" in
 		;;
 esac
 
-if [ -z "${latest}" ]; then
-	echo "$0: could not determine latest release version" >&2
+if [ -z "${repopath}" ]; then
+	echo "$0: could not determine repo path" >&2
     exit $failure
 fi
 
-echo "$latest"
+echo "$repopath"
